### ISSUE TITLE
NetAtmo Welcome

### ISSUE THREAD

**Issue by sprut666666** [athombv/com.netatmo#26] opened 2018-06-02 07:39 UTC
Hello,
NetAtmo v3.0.2 - 10.04.18 (AppStore)
The camera is connected but the flow does not work.
<img width="1115" alt="2018-06-02 10 38 38" src="https://user-images.githubusercontent.com/24498195/40872097-39775b2a-6651-11e8-9021-1d7193f9febf.png">

**Comment by WoutervdBrink** [comment] 2018-06-19 16:41
Hi there, thank you for your issue report.

This is a known bug in the Netatmo app. I have pushed a fix and it is currently awaiting feedback in QA, after which we will push the update to the app store.

I will close this issue now, as it is a duplicate of athombv/homey#2264.

**Closed by WoutervdBrink** 2018-06-19 16:41 UTC
Labels: bug
