### ISSUE TITLE
Netatmo app lost connection

### ISSUE THREAD

**Issue by ferdw** [athombv/com.netatmo#24] opened 2018-01-11 16:54 UTC
Had to login again an now only on device is available. Probably it will be possible to add again after delete the other one but then also the history is lost. 
![image](https://user-images.githubusercontent.com/10448491/34836537-741e8136-f6f8-11e7-930f-b6b38fc24db4.png)

**Comment by BasKiers** [comment] 2018-01-22 20:11
Hi, 

I could reproduce the issue and this should be fixed in v3.0.0 of the app. You can download this version in the app store by selecting the "beta" version of the app. Please note that you do need to re-pair your devices since this is also the rewrite to SDK2

Regards,
Bas

**Closed** 2018-01-23 19:48 UTC
Labels: bug
